# Generated by Django 5.2.8 on 2025-12-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clerk_user_id',
            field=models.CharField(blank=True, help_text='Unique Clerk user ID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('authority', 'Authority')], default='user', max_length=50),
        ),
    ]
