# Generated by Django 5.2.8 on 2025-11-20 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('reporter_name', models.CharField(blank=True, max_length=150)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_phone', models.CharField(blank=True, max_length=50)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('location_address', models.CharField(blank=True, max_length=512)),
                ('location_coordinates', models.JSONField(blank=True, null=True)),
                ('location_accuracy', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='Submitted', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
