# Generated by Django 5.2.8 on 2025-11-20 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='location_accuracy',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='location_coordinates',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='issue',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='issue',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issue',
            name='photos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='report_id',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
