# Generated by Django 5.2.8 on 2025-11-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_issue_photos_issuephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='issuephoto',
            name='uploaded_at',
        ),
    ]
