# Generated by Django 5.2.8 on 2025-11-25 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_add_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IssueVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='issues.issue')),
            ],
            options={
                'unique_together': {('issue', 'voter_email')},
            },
        ),
    ]
