# Generated by Django 5.2.8 on 2026-01-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issue_downvotes_issuevote_vote_type_issuecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
