# Generated by Django 5.2.8 on 2026-01-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_issue_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
