# Generated by Django 5.2.8 on 2026-01-27 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_issue_is_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_views', to='issues.issue')),
            ],
            options={
                'unique_together': {('issue', 'viewer_id')},
            },
        ),
    ]
