# Generated by Django 5.2.8 on 2026-02-23 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_issueview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('notification_type', models.CharField(choices=[('status_change', 'Status Change'), ('resolved', 'Issue Resolved'), ('rejected', 'Issue Rejected'), ('in_progress', 'In Progress'), ('under_review', 'Under Review')], default='status_change', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='issues.issue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
